name: Build immortalwrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 \
            libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lld llvm lrzsz mkisofs msmtp \
            nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply \
            python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig \
            texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
      - name: Clone source code
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          cd /workdir
          git clone https://github.com/immortalwrt/immortalwrt
      - name: pre build
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          cd /workdir
          cd ./immortalwrt
          echo 'src-git mihomo https://github.com/morytyann/OpenWrt-mihomo' >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: build
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          cd /workdir
          cd ./immortalwrt
          wget https://raw.githubusercontent.com/rekey/openwrt/refs/heads/main/.config
          make V=s -j$(nproc)

