name: Build openwrt-base image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y curl wget
          
      - name: Install Docker
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo usermod -aG docker ${USER}
          sudo systemctl enable --now docker
      
      - name: Build image
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget https://raw.githubusercontent.com/rekey/docker/refs/heads/master/openwrt-base/Dockerfile
          docker build . -t rekey/openwrt-base
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN
          docker push rekey/openwrt-debian-base
