name: Build openwrt builder image
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: true
        default: "false"

env:
  IMAGE_NAME: openwrt-builder
  DOKCERFILE_DIR: https://github.com/rekey/openwrt/raw/main/Dockerfiles
  DOKCERFILE_NAME: openwrt-builder.Dockerfile
  GHCR: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y curl wget
          
      - name: Install Docker
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo usermod -aG docker ${USER}
          sudo systemctl enable --now docker
      
      - name: Build image
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget $DOKCERFILE_DIR/$DOKCERFILE_NAME
          docker build -t $GHCR/${{ secrets.DOCKER_USER }}/$IMAGE_NAME -f ./$DOKCERFILE_NAME .

      - name: Push image
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker login $GHCR -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.GHCR_TOKEN }}
          docker push $GHCR/${{ secrets.DOCKER_USER }}/$IMAGE_NAME
