name: check disk

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo df -h
          pwd